// Default rules, categories, and machine configs. These are seeded into SQLite
// on first run and are fully editable afterwards via the Rules editor.

import type {
  Category,
  GlobalSettings,
  Machine,
  PrepRule,
} from './types.js';

export const SEED_CATEGORIES: Category[] = [
  {
    id: 'socks_underwear',
    name: 'Underwear & Socks',
    icon: '🧦',
    color: '#6366f1',
    order: 1,
    washTemp: 2,
    dryMethod: 'machine',
    dryDefault: { heat: 'Low', minutes: 60 },
    mergeIntoId: 'general',
    exclusions: [],
    meshBag: null,
    maxItems: null,
    routeToService: false,
  },
  {
    id: 'bras',
    name: 'Bras',
    icon: '👙',
    color: '#ec4899',
    order: 2,
    washTemp: 2,
    dryMethod: 'hang',
    dryDefault: null,
    mergeIntoId: null,
    exclusions: [],
    meshBag: 'bra',
    maxItems: 2,
    routeToService: false,
  },
  {
    id: 'towels',
    name: 'Towels',
    icon: '🧖',
    color: '#0ea5e9',
    order: 3,
    washTemp: 4,
    dryMethod: 'machine',
    dryDefault: { heat: 'Medium', minutes: 60 },
    mergeIntoId: null,
    exclusions: ['bath_mats', 'kitchen_towels'],
    meshBag: null,
    maxItems: null,
    routeToService: false,
  },
  {
    id: 'general',
    name: 'General Clothes',
    icon: '👕',
    color: '#22c55e',
    order: 4,
    washTemp: 2,
    dryMethod: 'machine',
    dryDefault: { heat: 'Low', minutes: 60 },
    mergeIntoId: null,
    exclusions: [],
    meshBag: null,
    maxItems: null,
    routeToService: false,
  },
  {
    id: 'delicates',
    name: 'Delicates',
    icon: '🌸',
    color: '#a855f7',
    order: 5,
    washTemp: 2,
    dryMethod: 'rack',
    dryDefault: null,
    mergeIntoId: null,
    exclusions: [],
    meshBag: 'normal',
    maxItems: null,
    routeToService: false,
  },
  {
    id: 'sheets',
    name: 'Bed Sheets',
    icon: '🛏️',
    color: '#f59e0b',
    order: 6,
    washTemp: 4,
    dryMethod: 'machine',
    dryDefault: { heat: 'Medium', minutes: 60 },
    mergeIntoId: null,
    exclusions: [],
    meshBag: null,
    maxItems: null,
    routeToService: false,
  },
  {
    id: 'special_delicates',
    name: 'Special Delicates',
    icon: '💎',
    color: '#64748b',
    order: 7,
    washTemp: null,
    dryMethod: 'none',
    dryDefault: null,
    mergeIntoId: null,
    exclusions: [],
    meshBag: null,
    maxItems: null,
    routeToService: true,
  },
];

export const SEED_PREP_RULES: PrepRule[] = [
  {
    id: 'darn_tough',
    text: 'Turn Darn Tough socks inside out',
    icon: '🧦',
    appliesTo: ['socks_underwear', 'general'],
  },
  {
    id: 'decals',
    text: 'Turn clothes with decals or prints inside out',
    icon: '👕',
    appliesTo: ['general'],
  },
  {
    id: 'bra_bag',
    text: 'Put bras in the bra mesh bag (max 2 per bag)',
    icon: '👙',
    appliesTo: ['bras'],
  },
  {
    id: 'delicate_bag',
    text: 'Put delicates in a normal mesh bag',
    icon: '🧺',
    appliesTo: ['delicates'],
  },
];

export const SEED_SETTINGS: GlobalSettings = {
  maxFillFraction: 0.75,
  detergentMark1MaxFill: 'half',
  extraRinseAlways: true,
  vinegarInSoftenerTray: true,
  vinegarNote: 'Distilled vinegar in the softener tray, a little less than max',
  leaveDoorOpenAfter: true,
  emptyLintTrapBeforeDry: true,
  quietHours: { enabled: true, start: '22:00', end: '07:00' },
  defaultWashMinutes: 55,
  defaultDryMinutes: 60,
};

// --- LG washer (front-load, WM3400-series layout) ---

const WASHER: Machine = {
  id: 'washer',
  name: 'LG Washer',
  model: 'WM3400CW',
  tempScale: {
    '1': 'Tap Cold',
    '2': 'Cold',
    '3': 'Warm',
    '4': 'Hot-Warm',
    '5': 'Hot',
  },
  panel: {
    width: 1080,
    height: 300,
    controls: [
      { id: 'logo', type: 'logo', x: 24, y: 136, w: 60, h: 30, label: 'LG' },
      {
        id: 'cyclesLeft',
        type: 'text',
        x: 104,
        y: 84,
        w: 130,
        h: 150,
        labels: ['Normal', 'Heavy Duty', 'Bedding', 'Towels'],
      },
      { id: 'dial', type: 'dial', x: 250, y: 96, w: 120, h: 120, label: 'Cycle' },
      {
        id: 'cyclesRight',
        type: 'text',
        x: 386,
        y: 84,
        w: 150,
        h: 150,
        labels: ['Delicates', 'Perm. Press', 'Speed Wash', 'Tub Clean'],
      },
      { id: 'powerBtn', type: 'button', x: 256, y: 238, w: 44, h: 44, label: 'Power' },
      { id: 'startBtn', type: 'button', x: 330, y: 238, w: 44, h: 44, label: 'Start' },
      {
        id: 'tempLeds',
        type: 'ledGroup',
        x: 560,
        y: 66,
        w: 120,
        h: 150,
        label: 'Temp.',
        labels: ['Hot', 'Hot-Warm', 'Warm', 'Cold', 'Tap Cold'],
      },
      { id: 'tempBtn', type: 'button', x: 560, y: 230, w: 120, h: 32, label: 'Temp.' },
      { id: 'spinBtn', type: 'button', x: 692, y: 230, w: 76, h: 32, label: 'Spin' },
      { id: 'soilBtn', type: 'button', x: 778, y: 230, w: 76, h: 32, label: 'Soil' },
      { id: 'display', type: 'display', x: 700, y: 66, w: 110, h: 46, label: '88' },
      { id: 'delayBtn', type: 'button', x: 868, y: 66, w: 184, h: 34, label: 'Delay Wash' },
      { id: 'coldWashBtn', type: 'button', x: 868, y: 110, w: 184, h: 34, label: 'Cold Wash' },
      {
        id: 'extraRinseBtn',
        type: 'button',
        x: 868,
        y: 154,
        w: 184,
        h: 34,
        label: 'Extra Rinse',
      },
    ],
  },
  steps: [
    {
      id: 'load',
      title: 'Load the drum',
      instruction:
        'Open the door and load the sorted clothes. Keep the drum no more than 3/4 full.',
      highlight: [],
    },
    {
      id: 'detergent',
      title: 'Add detergent',
      instruction:
        'Open the dispenser drawer. Detergent to mark 1 if the drum is under half full, otherwise mark 2.',
      highlight: [],
    },
    {
      id: 'vinegar',
      title: 'Add vinegar',
      instruction:
        'Pour distilled vinegar into the fabric softener tray, a little less than the max line.',
      highlight: [],
    },
    {
      id: 'power',
      title: 'Power on',
      instruction: 'Press the Power button.',
      highlight: ['powerBtn'],
    },
    {
      id: 'cycle',
      title: 'Select the cycle',
      instruction:
        'Turn the dial to the cycle: Normal for general, Towels, Bedding for sheets, Delicates for the mesh-bag load.',
      highlight: ['dial', 'cyclesLeft', 'cyclesRight'],
    },
    {
      id: 'temp',
      title: 'Set the temperature',
      instruction: 'Press Temp. until the correct level lights up for this load.',
      highlight: ['tempBtn', 'tempLeds'],
    },
    {
      id: 'extra_rinse',
      title: 'Turn on Extra Rinse',
      instruction: 'Press Extra Rinse. We always use an extra rinse.',
      highlight: ['extraRinseBtn'],
    },
    {
      id: 'start',
      title: 'Start the wash',
      instruction:
        'Press Start/Pause to begin. (To schedule around bedtime, use Delay Wash first.)',
      highlight: ['startBtn', 'delayBtn'],
    },
  ],
};

// --- LG dryer DLE3400W ---

const DRYER: Machine = {
  id: 'dryer',
  name: 'LG Dryer',
  model: 'DLE3400W',
  panel: {
    width: 1080,
    height: 300,
    controls: [
      { id: 'logo', type: 'logo', x: 24, y: 136, w: 60, h: 30, label: 'LG' },
      {
        id: 'cyclesLeft',
        type: 'text',
        x: 104,
        y: 84,
        w: 130,
        h: 150,
        labels: ['Normal', 'Heavy Duty', 'Bedding', 'Towels'],
      },
      { id: 'dial', type: 'dial', x: 250, y: 96, w: 120, h: 120, label: 'Cycle' },
      {
        id: 'cyclesRight',
        type: 'text',
        x: 386,
        y: 84,
        w: 150,
        h: 150,
        labels: ['Delicates', 'Perm. Press', 'Speed Dry', 'Air Dry'],
      },
      { id: 'powerBtn', type: 'button', x: 256, y: 238, w: 44, h: 44, label: 'Power' },
      { id: 'startBtn', type: 'button', x: 330, y: 238, w: 44, h: 44, label: 'Start' },
      {
        id: 'dryLevelLeds',
        type: 'ledGroup',
        x: 560,
        y: 66,
        w: 108,
        h: 150,
        label: 'Dry Level',
        labels: ['Very', 'Normal', 'Damp'],
      },
      { id: 'dryLevelBtn', type: 'button', x: 560, y: 230, w: 108, h: 32, label: 'Dry Level' },
      {
        id: 'tempLeds',
        type: 'ledGroup',
        x: 678,
        y: 66,
        w: 108,
        h: 150,
        label: 'Temp.',
        labels: ['Cool', 'High', 'Medium', 'Low'],
      },
      { id: 'tempBtn', type: 'button', x: 678, y: 230, w: 108, h: 32, label: 'Temp.' },
      {
        id: 'timeLeds',
        type: 'ledGroup',
        x: 796,
        y: 66,
        w: 92,
        h: 150,
        label: 'Time Dry',
        labels: ['60 min', '40', '20'],
      },
      { id: 'timeBtn', type: 'button', x: 796, y: 230, w: 92, h: 32, label: 'Time Dry' },
      { id: 'display', type: 'display', x: 900, y: 66, w: 110, h: 46, label: '88' },
      { id: 'wrinkleBtn', type: 'button', x: 900, y: 122, w: 164, h: 30, label: 'Wrinkle Care' },
      { id: 'moreTimeBtn', type: 'button', x: 900, y: 158, w: 78, h: 28, label: 'More Time' },
      { id: 'lessTimeBtn', type: 'button', x: 986, y: 158, w: 78, h: 28, label: 'Less Time' },
      { id: 'energyBtn', type: 'button', x: 900, y: 192, w: 164, h: 28, label: 'Energy Saver' },
    ],
  },
  steps: [
    {
      id: 'lint',
      title: 'Empty the lint trap',
      instruction:
        'Pull out the lint filter and clear all lint before every dry. A clogged filter is a fire risk and slows drying.',
      highlight: [],
    },
    {
      id: 'load',
      title: 'Load the damp clothes',
      instruction: 'Transfer the washed load into the dryer. Skip anything that hang dries.',
      highlight: [],
    },
    {
      id: 'power',
      title: 'Power on',
      instruction: 'Press the Power button.',
      highlight: ['powerBtn'],
    },
    {
      id: 'cycle',
      title: 'Select a Manual Dry cycle',
      instruction:
        'The auto sensor cycle is unreliable. Turn the dial to a Manual Dry cycle (Speed Dry) so you control time and heat.',
      highlight: ['dial', 'cyclesRight'],
    },
    {
      id: 'temp',
      title: 'Set the heat',
      instruction: 'Press Temp. to the recommended heat (Low for setting-2 loads).',
      highlight: ['tempBtn', 'tempLeds'],
    },
    {
      id: 'time',
      title: 'Set the time',
      instruction: 'Press Time Dry to the recommended minutes (60 for setting-2 loads).',
      highlight: ['timeBtn', 'timeLeds'],
    },
    {
      id: 'start',
      title: 'Start drying',
      instruction: 'Press Start/Pause to begin.',
      highlight: ['startBtn'],
    },
  ],
};

export const SEED_MACHINES: Machine[] = [WASHER, DRYER];
